//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Pricing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSupport.Resources.Views.Pricing.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% discount for full year payment.
        /// </summary>
        public static string DiscountHeader {
            get {
                return ResourceManager.GetString("DiscountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for 12 months is 54 EUR instead of 60 EUR.
        /// </summary>
        public static string DiscountParagraph {
            get {
                return ResourceManager.GetString("DiscountParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 EUR per month.
        /// </summary>
        public static string MoneyHeader {
            get {
                return ResourceManager.GetString("MoneyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hidden costs.
        /// </summary>
        public static string MoneyParagraph {
            get {
                return ResourceManager.GetString("MoneyParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We accept PayPal.
        /// </summary>
        public static string PayPalHeader {
            get {
                return ResourceManager.GetString("PayPalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As well as all major credit cards through PayPal service.
        /// </summary>
        public static string PayPalParagraph {
            get {
                return ResourceManager.GetString("PayPalParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL secured.
        /// </summary>
        public static string SSLHeader {
            get {
                return ResourceManager.GetString("SSLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your chats are secure with SSL encryption.
        /// </summary>
        public static string SSLParagraph {
            get {
                return ResourceManager.GetString("SSLParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 days trial period.
        /// </summary>
        public static string TrialPeriodHeader {
            get {
                return ResourceManager.GetString("TrialPeriodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try and test for 14 days. No strings attached.
        /// </summary>
        public static string TrialPeriodParagraph {
            get {
                return ResourceManager.GetString("TrialPeriodParagraph", resourceCulture);
            }
        }
    }
}
